site_name: BI-OSY Wiki
site_description: Wiki k předmětu BI-OSY (Operační systémy) na FIT ČVUT
site_url: https://martulens.github.io/osyWiki/
theme:
  name: material
  language: cs
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: indigo
      accent: indigo

docs_dir: wiki

markdown_extensions:
  - tables
  - toc:
      permalink: true
      toc_depth: "2-3"
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

extra_css:
  - stylesheets/extra.css
